ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLESPACE dgt_data DATAFILE 'dgt_data.dbf' SIZE 100M AUTOEXTEND ON;
CREATE TABLESPACE dgt_index DATAFILE 'dgt_index.dbf' SIZE 50M AUTOEXTEND ON;
CREATE TABLESPACE dgt_log DATAFILE 'dgt_log.dbf' SIZE 50M AUTOEXTEND ON;
CREATE TABLESPACE dgt_dw DATAFILE 'dgt_stats.dbf' SIZE 50M AUTOEXTEND ON;

