/*
ALTER SESSION SET CONTAINER = FREEPDB1;
-- Dueño
CREATE USER dgt_admin IDENTIFIED BY uoc;
-- Operativos
CREATE USER agente_gc01 IDENTIFIED BY 1234;
CREATE USER funcionario01 IDENTIFIED BY 1234;
CREATE USER analista01 IDENTIFIED BY 1234;

*/

ALTER SESSION SET CONTAINER = FREEPDB1;

-- Dueño de la lógica
CREATE USER dgt_admin IDENTIFIED BY uoc;
ALTER USER dgt_admin QUOTA UNLIMITED ON dgt_data;
ALTER USER dgt_admin QUOTA UNLIMITED ON dgt_index;
ALTER USER dgt_admin QUOTA UNLIMITED ON dgt_log;
ALTER USER dgt_admin QUOTA UNLIMITED ON dgt_dw;

-- Usuarios operativos
CREATE USER agente_gc01 IDENTIFIED BY 1234;
CREATE USER funcionario01 IDENTIFIED BY 1234;
CREATE USER analista01 IDENTIFIED BY 1234;