ALTER SESSION SET CONTAINER = FREEPDB1;
-- Dueño
CREATE USER dgt_admin IDENTIFIED BY uoc;
-- Operativos
CREATE USER agente_gc01 IDENTIFIED BY 1234;
CREATE USER funcionario01 IDENTIFIED BY 1234;
CREATE USER analista01 IDENTIFIED BY 1234;

