ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = dgt_admin;



-- TABLA COMUNIDAD AUTONOMA
CREATE TABLE comunidadautonoma (
    idccaa NUMBER
        GENERATED ALWAYS AS IDENTITY
        CONSTRAINT pk_ccaa PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
        CONSTRAINT uq_ccaa_nombre UNIQUE,
    f_ccaa NUMBER(4, 2) NOT NULL
)TABLESPACE dgt_data;


-- PROVINCIA

CREATE TABLE provincia (
    idprovincia NUMBER
        GENERATED ALWAYS AS IDENTITY
        CONSTRAINT pk_provincia PRIMARY KEY,
    idccaa      NUMBER NOT NULL,
    nombre      VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_provincia_ccaa FOREIGN KEY ( idccaa )
        REFERENCES comunidadautonoma ( idccaa ),
    CONSTRAINT uq_provincia UNIQUE ( idccaa,
                                     nombre )
)
TABLESPACE dgt_data;


--MUNICIPIO
CREATE TABLE municipio (
    idmunicipio NUMBER
        GENERATED ALWAYS AS IDENTITY
        CONSTRAINT pk_municipio PRIMARY KEY,
    idprovincia NUMBER NOT NULL,
    nombre      VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_municipio_provincia FOREIGN KEY ( idprovincia )
        REFERENCES provincia ( idprovincia ),
    CONSTRAINT uq_municipio UNIQUE ( idprovincia,
                                     nombre )
)
TABLESPACE dgt_data; 


CREATE TABLE etiquetaambiental (
    idetiqueta NUMBER
        GENERATED ALWAYS AS IDENTITY
        CONSTRAINT pk_etiqueta PRIMARY KEY,
    codigo     VARCHAR2(20) NOT NULL
        CONSTRAINT uq_etiqueta UNIQUE
)
TABLESPACE dgt_data;



--VEHICULO
CREATE TABLE vehiculo (
    idvehiculo               NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT pk_vehiculo PRIMARY KEY,
    matricula                VARCHAR2(10) NOT NULL CONSTRAINT uq_matricula UNIQUE,
    marca                    VARCHAR2(50) NOT NULL,
    modelo                   VARCHAR2(50) NOT NULL,
    color                    VARCHAR2(30) NOT NULL,
    esimportado              NUMBER(1) NOT NULL,
    fechaimportacion         DATE,
    superoprimerainspeccion  NUMBER(1) NOT NULL,
    idetiqueta               NUMBER NOT NULL,
    fechaultimaitv           DATE,
    CONSTRAINT fk_vehiculo_etiqueta FOREIGN KEY (idetiqueta) REFERENCES etiquetaambiental (idetiqueta),
    CONSTRAINT chk_esimportado_bool CHECK (esimportado IN (0, 1)),
    CONSTRAINT chk_supero_itv_bool CHECK (superoprimerainspeccion IN (0, 1)),
    CONSTRAINT chk_importacion CHECK ((esimportado = 1 AND fechaimportacion IS NOT NULL) OR (esimportado = 0 AND fechaimportacion IS NULL))
)TABLESPACE dgt_data;

-- TABLA AUXILIAR PARA GENERAR LAS LETRAS DE LAS MATRICULAS
CREATE TABLE matricula_letras (
    id NUMBER PRIMARY KEY CHECK (id = 1),
    letras VARCHAR2(3) NOT NULL
)TABLESPACE dgt_data;

CREATE TABLE TipoCombustible (
    idCombustible NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcionCombustible VARCHAR2(20) NOT NULL,
    f_comb NUMBER(5,2) NOT NULL,
    CONSTRAINT uq_desc_combustible UNIQUE (descripcionCombustible)
)TABLESPACE dgt_data;


-- HOMOLOGACION
CREATE TABLE homologacion (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_homologacion PRIMARY KEY,
    contrasenahomologacion VARCHAR2(100) NOT NULL,
    autoridadhomologacion VARCHAR2(100) NOT NULL,
    fabricante VARCHAR2(100) NOT NULL,
    fechahomologacion DATE NOT NULL,
    idvehiculo NUMBER NOT NULL,
    CONSTRAINT fk_homologacion_vehiculo FOREIGN KEY (idvehiculo) REFERENCES vehiculo (idvehiculo),
    CONSTRAINT uq_homologacion_vehiculo UNIQUE (idvehiculo)
) TABLESPACE dgt_data;



-- TIPO DE VEHICULO
CREATE TABLE TipoVehiculo (
    idTipoVehiculo      NUMBER(3)       PRIMARY KEY,
    descripcionVehiculo VARCHAR2(50)   NOT NULL,
    itv_especial        NUMBER(1)       DEFAULT 0 
                                      CHECK (itv_especial IN (0,1)),
    F_tipo              NUMBER(3,2)     NOT NULL
)tablespace dgt_data;

--
-- TABLA FICHA TECNICA
CREATE TABLE FichaTecnica (
    idFicha NUMBER(10) PRIMARY KEY,
    VIN VARCHAR2(50) NOT NULL,
    cilindrada NUMBER(6) NOT NULL,
    potenciaCV NUMBER(4) NOT NULL,
    potenciaKw NUMBER(4,1) NOT NULL,
    numeroPlazas NUMBER(2) NOT NULL,
    mma NUMBER(6) NOT NULL,
    dimensiones VARCHAR2(100) NOT NULL,
    fechaFabricacion DATE NOT NULL,
    idTipoVehiculo NUMBER(3),
    idVehiculo NUMBER(10),
    idCombustible NUMBER(3),
    CONSTRAINT FK_FICHA_TIPOVEHICULO FOREIGN KEY (idTipoVehiculo) REFERENCES TipoVehiculo(idTipoVehiculo),
    CONSTRAINT FK_FICHA_VEHICULO FOREIGN KEY (idVehiculo) REFERENCES Vehiculo(idvehiculo),
    CONSTRAINT FK_FICHA_COMBUSTIBLE FOREIGN KEY (idCombustible) REFERENCES TipoCombustible(idCombustible),
    CONSTRAINT uq_ficha_vehiculo UNIQUE (idVehiculo)
) TABLESPACE dgt_data;


CREATE TABLE FactorEmisiones (
    id        NUMBER
                 GENERATED BY DEFAULT AS IDENTITY
                 CONSTRAINT pk_factor_emisiones PRIMARY KEY,
    co2Min    NUMBER(4)      NOT NULL,
    co2Max    NUMBER(4)      NOT NULL,
    f_emis    NUMBER(3,2)    NOT NULL
) TABLESPACE dgt_data;

CREATE TABLE Emisiones (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_emisiones PRIMARY KEY,
    emisionesCO2 NUMBER(4) NOT NULL,
    idVehiculo NUMBER NOT NULL,
    idFactorEmisiones NUMBER NOT NULL,
    CONSTRAINT fk_emisiones_vehiculo
        FOREIGN KEY (idVehiculo)
        REFERENCES Vehiculo(idVehiculo),
    CONSTRAINT fk_emisiones_factor
        FOREIGN KEY (idFactorEmisiones)
        REFERENCES FactorEmisiones(id),
    CONSTRAINT uq_emisiones_vehiculo
        UNIQUE (idVehiculo)
) TABLESPACE dgt_data;



--
CREATE TABLE estadoexpediente (
    idestadoexp NUMBER
        GENERATED ALWAYS AS IDENTITY
        CONSTRAINT pk_estadoexp PRIMARY KEY,
    descripcion VARCHAR2(50) NOT NULL
        CONSTRAINT uq_estadoexp_desc UNIQUE
)
TABLESPACE dgt_data;




CREATE TABLE Expediente (
    idExpediente NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT pk_expediente PRIMARY KEY,
    fechaInicio DATE NOT NULL,
    fechaFinalizacion DATE,
    idVehiculo NUMBER NOT NULL,
    idEstadoExp NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT fk_expediente_vehiculo FOREIGN KEY (idVehiculo) REFERENCES Vehiculo(idVehiculo),
    CONSTRAINT fk_expediente_estado FOREIGN KEY (idEstadoExp) REFERENCES EstadoExpediente(idEstadoExp),
    CONSTRAINT uq_expediente_vehiculo UNIQUE (idVehiculo)
) TABLESPACE dgt_data;


CREATE TABLE HistoricoEstados (
    idHistorico NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT pk_historico_estados PRIMARY KEY,
    idExpediente NUMBER NOT NULL,
    fechaCambio DATE NOT NULL,
    idEstadoExp NUMBER NOT NULL,
    CONSTRAINT fk_hist_exp FOREIGN KEY (idExpediente) REFERENCES Expediente(idExpediente),
    CONSTRAINT fk_hist_estado FOREIGN KEY (idEstadoExp) REFERENCES EstadoExpediente(idEstadoExp)
) TABLESPACE dgt_data;


