ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = dgt_admin;



-- tabla

CREATE TABLE LOG_Auditoria (
    idLog               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_registro      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario            VARCHAR2(100) DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER'),
    nombreProcedimiento VARCHAR2(255),
    parametroIN        CLOB,
    parametroOUT       CLOB  -- Aquí guardaremos el RSP ('OK' o 'ERROR...')
)tablespace dgt_log;
